import os
import telebot

API_TOKEN = os.getenv("API_TOKEN")
bot = telebot.TeleBot(API_TOKEN, threaded=True)

ADMIN_PRIMARY = 5145154527
ADMIN_SECONDARY = 8878290572

CHANNEL_ID = -1003763276411  
CHANNEL_LINK = "https://t.me/evee7x"

DB_USERS = "users_data.json"
DB_KEYS = "keys_store.json"
DB_REDEEM = "redeem_codes.json"
DB_PRICES = "prices_config.json"
DB_CONFIG = "bot_config.json"

RANKS = {
    "silver":  {"name_ar": "🥈 الفضي", "name_en": "🥈 Silver", "name_fr": "🥈 Argent", "name_es": "🥈 Plata", "name_vi": "🥈 Bạc", "points_needed": 200, "discount": 0.01},
    "gold":    {"name_ar": "🥇 الذهبي", "name_en": "🥇 Gold", "name_fr": "🥇 Or", "name_es": "🥇 Oro", "name_vi": "🥇 Vàng", "points_needed": 600, "discount": 0.02},
    "diamond": {"name_ar": "💎 الماسي", "name_en": "💎 Diamond", "name_fr": "💎 Diamant", "name_es": "💎 Diamante", "name_vi": "💎 Kim cương", "points_needed": 1500, "discount": 0.03},
    "hero":    {"name_ar": "⚡ الهيرو", "name_en": "⚡ Hero", "name_fr": "⚡ Héros", "name_es": "⚡ Héroe", "name_vi": "⚡ Anh hùng", "points_needed": 3500, "discount": 0.04},
    "master":  {"name_ar": "👑 الماستر", "name_en": "👑 Master", "name_fr": "👑 Maître", "name_es": "👑 Maestro", "name_vi": "👑 Bậc thầy", "points_needed": 7000, "discount": 0.045},
    "legend":  {"name_ar": "🏆 الأسطورة", "name_en": "🏆 Legend", "name_fr": "🏆 Légende", "name_es": "🏆 Leyenda", "name_vi": "🏆 Huyền thoại", "points_needed": 12000, "discount": 0.05}
}

TICKET_CATEGORIES = {
    "technical": {"ar": "🔧 مشكلة تقنية", "en": "🔧 Technical Issue", "fr": "🔧 Problème technique", "es": "🔧 Problema técnico", "vi": "🔧 Lỗi kỹ thuật"},
    "payment": {"ar": "💰 مشكلة دفع", "en": "💰 Payment Issue", "fr": "💰 Problème paiement", "es": "💰 Problema de pago", "vi": "💰 Lỗi thanh toán"},
    "product": {"ar": "📦 مشكلة منتج", "en": "📦 Product Issue", "fr": "📦 Problème produit", "es": "📦 Problema producto", "vi": "📦 Lỗi sản phẩm"},
    "suggestion": {"ar": "💡 اقتراح", "en": "💡 Suggestion", "fr": "💡 Suggestion", "es": "💡 Sugerencia", "vi": "💡 Đề xuất"},
    "other": {"ar": "📝 أخرى", "en": "📝 Other", "fr": "📝 Autre", "es": "📝 Otro", "vi": "📝 Khác"}
}

LOCALES = {
    "ar": {
        "welcome": "🌟 <b>مرحباً بك في متجرنا!</b>\n\n🌐 اختر لغتك المفضلة:",
        "must_join": "🔐 يجب الاشتراك بقناتنا أولاً!",
        "check_btn": "✅ تحقق من الاشتراك",
        "join_channel": "📢 اشترك في القناة",
        "main_menu_title": "🏠 <b>مرحباً {name}!</b>\n\n✨ <i>اختر ما يسعدك من القائمة:</i>",
        "btn_account": "👤 حسابي",
        "btn_shop": "🛍️ المتجر",
        "btn_rewards": "🎁 المكافآت",
        "btn_entertainment": "🎮 الترفيه",
        "btn_support": "💬 الدعم",
        "btn_settings": "⚙️ الإعدادات",
        "btn_admin": "👑 الإدارة",
        "btn_back": "🔙 رجوع",
        "account_title": "👤 <b>━━ حسابي الشخصي ━━</b>",
        "account_desc": "✨ كل بياناتك في مكان واحد",
        "btn_balance": "💰 رصيدي",
        "btn_my_id": "🆔 معلوماتي",
        "btn_my_rank": "🏆 رتبتي",
        "btn_referral": "🔗 الإحالة",
        "btn_my_purchases": "📜 مشترياتي",
        "rewards_title": "🎁 <b>━━ مركز المكافآت ━━</b>",
        "rewards_desc": "✨ احصد مكافآتك المجانية!",
        "btn_daily_bonus": "✨ المكافأة اليومية",
        "btn_redeem_code": "🎫 استرداد كود",
        "btn_quests": "🔥 المهام",
        "btn_flash_sale": "⚡ العروض الخاطفة",
        "entertainment_title": "🎮 <b>━━ مركز الترفيه ━━</b>",
        "entertainment_desc": "🎲 العب واكسب!",
        "btn_lootbox": "🎰 صندوق الحظ",
        "btn_wheel": "🎡 عجلة الحظ",
        "btn_leaderboard": "🏆 المتصدرون",
        "support_title": "💬 <b>━━ مركز الدعم ━━</b>",
        "support_desc": "🤝 فريقنا جاهز لخدمتك!",
        "btn_new_ticket": "🎫 تذكرة جديدة",
        "btn_my_tickets": "📋 تذاكري",
        "btn_request_product": "💡 طلب منتج",
        "btn_faq": "❓ الأسئلة الشائعة",
        "settings_title": "⚙️ <b>━━ الإعدادات ━━</b>",
        "settings_desc": "🎨 خصّص تجربتك!",
        "btn_change_lang": "🌐 تغيير اللغة",
        "btn_notifications": "🔔 الإشعارات",
        "btn_theme": "🎨 المظهر",
        "btn_privacy": "🔒 الخصوصية",
        "btn_about": "ℹ️ حول البوت",
        "btn_bot_dev": "برمجة البوت",
        "maintenance_on": "🛠️ <b>تم تفعيل وضع الصيانة</b>\n\n⚠️ البوت الآن غير متاح للمستخدمين",
        "maintenance_off": "✅ <b>تم إيقاف وضع الصيانة</b>\n\n🎉 البوت يعمل الآن بشكل طبيعي",
        "dev_info": "💻 <b>━━ برمجة البوت ━━</b>\n\n👨‍💻 <b>المبرمج:</b> @fkLJh00302\n\n💡 <i>للتواصل والحصول على بوت مثل هذا</i>",
        "balance_display": "💰 <b>━━ محفظتي ━━</b>\n\n┃ 👤 الآيدي: <code>{uid}</code>\n┃ 💵 الرصيد: <b>{points}</b> 💎\n┃ 🏆 الرتبة: {rank}\n┃ 🎯 الخصم: <b>{discount}%</b>\n┃ 👥 الدعوات: {invites}\n┃ 📊 التراكمي: {acc}\n┃ 🔥 سلسلة الأيام: {streak}\n╰━━━━━━━━━━━━╯",
        "daily_success": "🎁 <b>━━ مكافأة يومية ━━</b>\n\n🎉 حصلت على <b>+{gift}</b> 💎\n💰 رصيدك: <b>{balance}</b>\n🔥 سلسلة: <b>{streak}</b> يوم\n⏰ القادمة بعد 24 ساعة",
        "daily_wait": "⏳ <b>عد بعد {hours}س {mins}د</b>\n\n🔥 سلسلتك: <b>{streak}</b> يوم\n💡 لا تفوّت يومك!",
        "streak_bonus": "🔥🔥🔥 <b>مكافأة السلسلة!</b>\n\n🎊 {streak} أيام متتالية!\n🎁 بونص إضافي: <b>+{bonus}</b> 💎",
        "referral_msg": "🔗 <b>━━ نظام الإحالة ━━</b>\n\n┃ 👥 دعواتك: <b>{invites}</b>\n┃ 🎁 لكل دعوة: <b>{reward}</b> 💎\n┃ 💵 أرباحك: <b>{total}</b>\n╰━━━━━━━━━━━━╯\n\n📎 رابطك:\n<code>{link}</code>",
        "shop_header": "🛍️ <b>━━ المتجر ━━</b>\n\n┃ 💰 رصيدك: <b>{points}</b> 💎\n┃ 🏆 رتبتك: {rank}\n┃ 🎯 خصمك: <b>{disc}%</b>\n╰━━━━━━━━━━━━╯\n\n👇 اختر منتجك:",
        "purchase_success": "🎉✨ <b>━━ تم الشراء! ━━</b> ✨🎉\n\n┃ 📦 المنتج: <b>{prod}</b>\n┃ ⏱️ المدة: <b>{plan}</b>\n┃ 💰 الثمن: <b>{price}</b> 💎\n╰━━━━━━━━━━━━╯\n\n🔐 <b>مفتاحك:</b>\n<code>{key}</code>\n\n⚠️ <i>احفظه بمكان آمن!</i>",
        "ticket_categories": "🎫 <b>━━ تذكرة جديدة ━━</b>\n\n📂 اختر نوع المشكلة:",
        "ticket_write": "💬 اكتب تفاصيل مشكلتك...\n\n💡 <i>كلما كانت التفاصيل أكثر، كان الحل أسرع!</i>",
        "ticket_created": "✅ <b>━━ تم فتح التذكرة ━━</b>\n\n🎫 رقم: <code>#{tid}</code>\n📂 النوع: {category}\n⏳ سيرد فريقنا قريباً!",
        "ticket_reply_from_support": "💬 <b>━━ رد الدعم ━━</b>\n\n🎫 تذكرة: <code>#{tid}</code>\n👨‍💻 الرد:\n\n{reply}\n\n💡 <i>يمكنك الرد مباشرة</i>",
        "my_tickets_title": "📋 <b>━━ تذاكري ━━</b>",
        "no_tickets": "📭 لا توجد تذاكر",
        "flash_sale_active": "⚡ <b>━━ عرض خاطف! ━━</b>\n\n🔥 خصم <b>{discount}%</b> على:\n📦 <b>{product}</b>\n⏰ ينتهي خلال: <b>{remaining}</b>\n\n💨 <i>اسرع قبل الانتهاء!</i>",
        "no_flash_sale": "😴 <b>لا يوجد عرض خاطف حالياً</b>\n\n🔔 فعّل الإشعارات لتعرف أولاً!",
        "leaderboard_title": "🏆 <b>━━ المتصدرون ━━</b>\n\n👑 <i>أفضل 10 أعضاء بالمتجر:</i>\n",
        "notif_on": "🔔 الإشعارات <b>مفعّلة</b>",
        "notif_off": "🔕 الإشعارات <b>معطّلة</b>",
        "theme_title": "🎨 <b>━━ المظهر ━━</b>\n\n✨ <i>اختر ثيمك المفضل:</i>",
        "privacy_title": "🔒 <b>━━ الخصوصية ━━</b>\n\n• إخفاء اسمي من المتصدرين\n• عدم استقبال الإشعارات التسويقية",
        "about_title": "ℹ️ <b>━━ حول البوت ━━</b>\n\n🤖 <b>EVE Store Bot</b>\n📦 الإصدار: <b>3.0</b>\n👥 الأعضاء: <b>{users}</b>\n🛒 المبيعات: <b>{sales}</b>\n\n⚡ <i>مدعوم بأحدث التقنيات</i>",
        "faq_title": "❓ <b>━━ الأسئلة الشائعة ━━</b>\n\n1️⃣ <b>كيف أحصل على نقاط؟</b>\n└ المكافأة اليومية + الإحالة + المهام\n\n2️⃣ <b>كيف أشتري منتج؟</b>\n└ المتجر ← المنتج ← المدة ← شراء\n\n3️⃣ <b>كيف أرفع رتبتي؟</b>\n└ اجمع نقاط أكثر = رتبة أعلى تلقائياً\n\n4️⃣ <b>ما هو خصم الرتبة؟</b>\n└ كل رتبة تعطيك خصم ثابت على المشتريات",
        "captcha_title": "🛡️ <b>━━ فحص أمني ━━</b>\n\n⚠️ اضغط على <b>{name}</b> {emoji}",
        "captcha_correct": "✅ <b>تم التحقق!</b> 🎉",
        "captcha_wrong": "❌ خطأ! حاول مجدداً",
        "captcha_banned": "🚫 محظور لمدة ساعة",
        "banned": "🚫 <b>حسابك محظور!</b>",
        "maint_msg": "🛠️ <b>تحت الصيانة</b>\n⏳ نعود قريباً!",
        "insufficient_balance": "❌ رصيدك غير كافٍ!",
        "lang_changed": "✅ <b>تم تغيير اللغة!</b> 🎉",
        "shop_empty": "📭 <b>المتجر فارغ حالياً</b>",
        "ticket_chat_started": "💬 <b>━━ الدردشة مفتوحة ━━</b>\n\n✅ أنت الآن متصل بالدعم!\n\n📝 اكتب رسالتك هنا مباشرة\n🔒 اكتب /close لإنهاء الدردشة\n\n💡 <i>سيرد عليك الفريق قريباً...</i>",
        "ticket_user_msg": "👤 <b>رسالة من العميل:</b>\n\n{msg}",
        "ticket_closed": "🔒 <b>تم إغلاق التذكرة #{tid}</b>\n\n⭐ كيف تقيّم خدمتنا؟",
        "ticket_abuse_warn": "⚠️ <b>تحذير!</b>\n\nالعبث بنظام التذاكر قد يؤدي لحظر حسابك!",
        "gw_welcome_claim": "🎁 <b>مرحباً بك في العرض!</b>\n\n💎 <b>الجائزة:</b> {reward} نقطة\n👥 <b>المتبقي:</b> {remaining} من {max}\n⏰ <b>ينتهي بعد:</b> {time}\n\n✅ اضغط للحصول على جائزتك!",
        "gw_claim_btn": "🎁 استلام الجائزة الآن",
        "gw_success": "🎊 <b>مبروك! فزت بالجائزة!</b>\n\n💎 +{reward} نقطة أُضيفت لرصيدك!\n💰 <b>رصيدك الآن:</b> {balance}",
        "gw_already_claimed": "⚠️ <b>لقد استلمت هذه الجائزة من قبل!</b>",
        "gw_expired": "⏰ <b>انتهى وقت العرض!</b>\n\n💔 لقد فاتك، انتظر العرض القادم!",
        "gw_full": "😢 <b>تم استلام جميع الجوائز!</b>\n\n💔 وصلنا للحد الأقصى.",
        "gw_invalid": "❌ <b>رابط غير صحيح</b>",
        "buy_step_1": "⏳ <b>جاري معالجة الدفع...</b>",
        "buy_step_2": "🔐 <b>جاري تحضير مفتاحك الخاص...</b>",
        "buy_step_3": "📦 <b>جاري تغليف طلبك...</b>",
        "buy_step_4": "🎁 <b>يتم تسليم منتجك الآن...</b>",
        "buy_gift_msg": "🎁 <b>مبروك عليك المنتج!</b>\n\n✨ استمتع به وشاركه مع أصدقائك!",
        "notif_updated_on": "✅ <b>تم تفعيل الإشعارات</b>\n\n🔔 ستستقبل:\n• 📦 المنتجات الجديدة\n• ⚡ العروض الخاطفة\n• 🎁 المفاجآت الحصرية",
        "notif_updated_off": "✅ <b>تم إيقاف الإشعارات</b>\n\n🔕 لن تستقبل رسائل تسويقية\n💡 <i>ستستقبل تأكيدات الطلبات فقط</i>",
    },
    "en": {
        "welcome": "🌟 <b>Welcome to our Store!</b>\n\n🌐 Choose your language:",
        "must_join": "🔐 Join our channel first!",
        "check_btn": "✅ Check Subscription",
        "join_channel": "📢 Join Channel",
        "main_menu_title": "🏠 <b>Welcome {name}!</b>\n\n✨ <i>Choose from the menu:</i>",
        "btn_account": "👤 My Account",
        "btn_shop": "🛍️ Shop",
        "btn_rewards": "🎁 Rewards",
        "btn_entertainment": "🎮 Fun",
        "btn_support": "💬 Support",
        "btn_settings": "⚙️ Settings",
        "btn_admin": "👑 Admin",
        "btn_back": "🔙 Back",
        "account_title": "👤 <b>━━ My Account ━━</b>",
        "account_desc": "✨ All your info in one place",
        "btn_balance": "💰 Balance",
        "btn_my_id": "🆔 My Info",
        "btn_my_rank": "🏆 Rank",
        "btn_referral": "🔗 Referral",
        "btn_my_purchases": "📜 Purchases",
        "rewards_title": "🎁 <b>━━ Rewards Center ━━</b>",
        "rewards_desc": "✨ Claim your free rewards!",
        "btn_daily_bonus": "✨ Daily Bonus",
        "btn_redeem_code": "🎫 Redeem Code",
        "btn_quests": "🔥 Quests",
        "btn_flash_sale": "⚡ Flash Sales",
        "entertainment_title": "🎮 <b>━━ Entertainment ━━</b>",
        "entertainment_desc": "🎲 Play & Win!",
        "btn_lootbox": "🎰 Loot Box",
        "btn_wheel": "🎡 Lucky Wheel",
        "btn_leaderboard": "🏆 Leaderboard",
        "support_title": "💬 <b>━━ Support Center ━━</b>",
        "support_desc": "🤝 We're here to help!",
        "btn_new_ticket": "🎫 New Ticket",
        "btn_my_tickets": "📋 My Tickets",
        "btn_request_product": "💡 Request Product",
        "btn_faq": "❓ FAQ",
        "settings_title": "⚙️ <b>━━ Settings ━━</b>",
        "settings_desc": "🎨 Customize your experience!",
        "btn_change_lang": "🌐 Language",
        "btn_notifications": "🔔 Notifications",
        "btn_theme": "🎨 Theme",
        "btn_privacy": "🔒 Privacy",
        "btn_about": "ℹ️ About",
        "btn_bot_dev": "Bot Developer",
        "maintenance_on": "🛠️ <b>Maintenance mode ON</b>\n\n⚠️ Bot is now unavailable for users",
        "maintenance_off": "✅ <b>Maintenance mode OFF</b>\n\n🎉 Bot is now running normally",
        "dev_info": "💻 <b>━━ Bot Developer ━━</b>\n\n👨‍💻 <b>Programmer:</b> @fkLJh00302\n\n💡 <i>Contact for a bot like this</i>",
        "balance_display": "💰 <b>━━ My Wallet ━━</b>\n\n┃ 👤 ID: <code>{uid}</code>\n┃ 💵 Balance: <b>{points}</b> 💎\n┃ 🏆 Rank: {rank}\n┃ 🎯 Discount: <b>{discount}%</b>\n┃ 👥 Invites: {invites}\n┃ 📊 Total: {acc}\n┃ 🔥 Streak: {streak}\n╰━━━━━━━━━━━━╯",
        "daily_success": "🎁 <b>━━ Daily Bonus ━━</b>\n\n🎉 You got <b>+{gift}</b> 💎\n💰 Balance: <b>{balance}</b>\n🔥 Streak: <b>{streak}</b> days\n⏰ Next in 24 hours",
        "daily_wait": "⏳ <b>Come back in {hours}h {mins}m</b>\n\n🔥 Streak: <b>{streak}</b> days\n💡 Don't miss your day!",
        "streak_bonus": "🔥🔥🔥 <b>Streak Bonus!</b>\n\n🎊 {streak} days in a row!\n🎁 Extra bonus: <b>+{bonus}</b> 💎",
        "referral_msg": "🔗 <b>━━ Referral System ━━</b>\n\n┃ 👥 Invites: <b>{invites}</b>\n┃ 🎁 Per invite: <b>{reward}</b> 💎\n┃ 💵 Earnings: <b>{total}</b>\n╰━━━━━━━━━━━━╯\n\n📎 Your link:\n<code>{link}</code>",
        "shop_header": "🛍️ <b>━━ Shop ━━</b>\n\n┃ 💰 Balance: <b>{points}</b> 💎\n┃ 🏆 Rank: {rank}\n┃ 🎯 Discount: <b>{disc}%</b>\n╰━━━━━━━━━━━━╯\n\n👇 Select product:",
        "purchase_success": "🎉✨ <b>━━ Purchase Complete! ━━</b> ✨🎉\n\n┃ 📦 Product: <b>{prod}</b>\n┃ ⏱️ Duration: <b>{plan}</b>\n┃ 💰 Price: <b>{price}</b> 💎\n╰━━━━━━━━━━━━╯\n\n🔐 <b>Your Key:</b>\n<code>{key}</code>\n\n⚠️ <i>Save it safely!</i>",
        "ticket_categories": "🎫 <b>━━ New Ticket ━━</b>\n\n📂 Select issue type:",
        "ticket_write": "💬 Describe your issue...\n\n💡 <i>More details = faster solution!</i>",
        "ticket_created": "✅ <b>━━ Ticket Opened ━━</b>\n\n🎫 ID: <code>#{tid}</code>\n📂 Type: {category}\n⏳ Our team will respond soon!",
        "ticket_reply_from_support": "💬 <b>━━ Support Reply ━━</b>\n\n🎫 Ticket: <code>#{tid}</code>\n👨‍💻 Reply:\n\n{reply}\n\n💡 <i>You can reply directly</i>",
        "my_tickets_title": "📋 <b>━━ My Tickets ━━</b>",
        "no_tickets": "📭 No tickets found",
        "flash_sale_active": "⚡ <b>━━ Flash Sale! ━━</b>\n\n🔥 <b>{discount}%</b> OFF on:\n📦 <b>{product}</b>\n⏰ Ends in: <b>{remaining}</b>\n\n💨 <i>Hurry before it's gone!</i>",
        "no_flash_sale": "😴 <b>No active flash sales</b>\n\n🔔 Enable notifications!",
        "leaderboard_title": "🏆 <b>━━ Leaderboard ━━</b>\n\n👑 <i>Top 10 members:</i>\n",
        "notif_on": "🔔 Notifications <b>ON</b>",
        "notif_off": "🔕 Notifications <b>OFF</b>",
        "theme_title": "🎨 <b>━━ Theme ━━</b>\n\n✨ <i>Choose your style:</i>",
        "privacy_title": "🔒 <b>━━ Privacy ━━</b>\n\n• Hide from leaderboard\n• Block marketing messages",
        "about_title": "ℹ️ <b>━━ About ━━</b>\n\n🤖 <b>EVE Store Bot</b>\n📦 Version: <b>3.0</b>\n👥 Members: <b>{users}</b>\n🛒 Sales: <b>{sales}</b>\n\n⚡ <i>Powered by latest tech</i>",
        "faq_title": "❓ <b>━━ FAQ ━━</b>\n\n1️⃣ <b>How to earn points?</b>\n└ Daily bonus + Referrals + Quests\n\n2️⃣ <b>How to buy?</b>\n└ Shop → Product → Duration → Buy\n\n3️⃣ <b>How to rank up?</b>\n└ More points = higher rank auto\n\n4️⃣ <b>What's rank discount?</b>\n└ Each rank gives fixed discount",
        "captcha_title": "🛡️ <b>━━ Security ━━</b>\n\n⚠️ Press <b>{name}</b> {emoji}",
        "captcha_correct": "✅ <b>Verified!</b> 🎉",
        "captcha_wrong": "❌ Wrong! Try again",
        "captcha_banned": "🚫 Banned 1 hour",
        "banned": "🚫 <b>Account banned!</b>",
        "maint_msg": "🛠️ <b>Under Maintenance</b>",
        "insufficient_balance": "❌ Insufficient balance!",
        "lang_changed": "✅ <b>Language changed!</b> 🎉",
        "shop_empty": "📭 <b>Shop is empty</b>",
        "ticket_chat_started": "💬 <b>━━ Chat Opened ━━</b>\n\n✅ You're now connected to support!\n\n📝 Just type your messages here\n🔒 Type <code>/close</code> to end the chat\n\n💡 <i>Someone will reply shortly...</i>",
        "ticket_user_msg": "👤 <b>Message from client:</b>\n\n{msg}",
        "ticket_closed": "🔒 <b>Ticket #{tid} closed</b>\n\n⭐ Rate our service?",
        "ticket_abuse_warn": "⚠️ <b>Warning!</b>\n\nTicket abuse may result in ban!",
        "gw_welcome_claim": "🎁 <b>Welcome to the Giveaway!</b>\n\n💎 <b>Prize:</b> {reward} points\n👥 <b>Remaining:</b> {remaining} of {max}\n⏰ <b>Ends in:</b> {time}\n\n✅ Click to get your prize!",
        "gw_claim_btn": "🎁 Claim Prize Now",
        "gw_success": "🎊 <b>Congratulations! You won!</b>\n\n💎 +{reward} points added!\n💰 <b>Your balance:</b> {balance}",
        "gw_already_claimed": "⚠️ <b>You already claimed this prize!</b>",
        "gw_expired": "⏰ <b>Giveaway expired!</b>\n\n💔 Wait for the next one!",
        "gw_full": "😢 <b>All prizes claimed!</b>\n\n💔 Max users reached.",
        "gw_invalid": "❌ <b>Invalid link</b>",
        "buy_step_1": "⏳ <b>Processing payment...</b>",
        "buy_step_2": "🔐 <b>Preparing your key...</b>",
        "buy_step_3": "📦 <b>Packing your order...</b>",
        "buy_step_4": "🎁 <b>Delivering your product...</b>",
        "buy_gift_msg": "🎁 <b>Enjoy your product!</b>\n\n✨ Share with your friends!",
        "notif_updated_on": "✅ <b>Notifications ENABLED</b>\n\n🔔 You'll receive:\n• 📦 New products\n• ⚡ Flash sales\n• 🎁 Exclusive offers",
        "notif_updated_off": "✅ <b>Notifications DISABLED</b>\n\n🔕 No marketing messages\n💡 <i>You'll still get order confirmations</i>",
    },
    "fr": {
        "welcome": "🌟 <b>Bienvenue!</b>\n\n🌐 Choisissez votre langue:",
        "must_join": "🔐 Rejoignez la chaîne!",
        "check_btn": "✅ Vérifier",
        "join_channel": "📢 Rejoindre",
        "main_menu_title": "🏠 <b>Bonjour {name}!</b>\n\n✨ <i>Choisissez:</i>",
        "btn_account": "👤 Compte", "btn_shop": "🛍️ Boutique", "btn_rewards": "🎁 Récompenses",
        "btn_entertainment": "🎮 Jeux", "btn_support": "💬 Support", "btn_settings": "⚙️ Paramètres",
        "btn_admin": "👑 Admin", "btn_back": "🔙 Retour",
        "account_title": "👤 <b>━━ Mon Compte ━━</b>", "account_desc": "✨ Vos infos",
        "btn_balance": "💰 Solde", "btn_my_id": "🆔 Info", "btn_my_rank": "🏆 Rang",
        "btn_referral": "🔗 Parrainage", "btn_my_purchases": "📜 Achats",
        "rewards_title": "🎁 <b>━━ Récompenses ━━</b>", "rewards_desc": "✨ Réclamez!",
        "btn_daily_bonus": "✨ Bonus", "btn_redeem_code": "🎫 Code", "btn_quests": "🔥 Quêtes",
        "btn_flash_sale": "⚡ Ventes Flash",
        "entertainment_title": "🎮 <b>━━ Jeux ━━</b>", "entertainment_desc": "🎲 Jouez!",
        "btn_lootbox": "🎰 Coffre", "btn_wheel": "🎡 Roue", "btn_leaderboard": "🏆 Classement",
        "support_title": "💬 <b>━━ Support ━━</b>", "support_desc": "🤝 On est là!",
        "btn_new_ticket": "🎫 Nouveau", "btn_my_tickets": "📋 Mes Tickets",
        "btn_request_product": "💡 Demande", "btn_faq": "❓ FAQ",
        "settings_title": "⚙️ <b>━━ Paramètres ━━</b>", "settings_desc": "🎨 Personnalisez!",
        "btn_change_lang": "🌐 Langue", "btn_notifications": "🔔 Notifs",
        "btn_theme": "🎨 Thème", "btn_privacy": "🔒 Vie privée", "btn_about": "ℹ️ À propos",
        "btn_bot_dev": "Développeur",
        "maintenance_on": "🛠️ <b>Maintenance ON</b>",
        "maintenance_off": "✅ <b>Maintenance OFF</b>",
        "dev_info": "💻 <b>Développeur:</b> @fkLJh00302",
        "balance_display": "💰 <b>━━ Portefeuille ━━</b>\n\n💵 {points} 💎\n🏆 {rank}\n🎯 {discount}%\n🔥 Série: {streak}",
        "daily_success": "🎁 +{gift} 💎\n💰 {balance}\n🔥 {streak} jours", "daily_wait": "⏳ {hours}h {mins}m\n🔥 {streak}",
        "streak_bonus": "🔥 {streak} jours!\n🎁 +{bonus} 💎",
        "referral_msg": "🔗 👥 {invites}\n💵 {total}\n\n<code>{link}</code>",
        "shop_header": "🛍️ 💰 {points} | 🎯 {disc}%", "shop_empty": "📭 Vide",
        "purchase_success": "🎉 📦 {prod}\n⏱️ {plan}\n💰 {price}\n\n🔐 <code>{key}</code>",
        "ticket_categories": "🎫 <b>Type:</b>", "ticket_write": "💬 Votre message:",
        "ticket_created": "✅ #{tid}", "my_tickets_title": "📋 <b>Tickets</b>", "no_tickets": "📭",
        "flash_sale_active": "⚡ {discount}% OFF\n📦 {product}\n⏰ {remaining}", "no_flash_sale": "😴 Aucune vente",
        "leaderboard_title": "🏆 <b>━━ Classement ━━</b>\n",
        "notif_on": "🔔 ON", "notif_off": "🔕 OFF",
        "theme_title": "🎨 <b>Thème</b>", "privacy_title": "🔒 <b>Vie privée</b>",
        "about_title": "ℹ️ v3.0\n👥 {users}\n🛒 {sales}",
        "faq_title": "❓ <b>FAQ</b>\n\n1️⃣ Bonus + Parrainage\n2️⃣ Boutique → Acheter",
        "captcha_title": "🛡️ Cliquez: <b>{name}</b> {emoji}", "captcha_correct": "✅ Vérifié!",
        "captcha_wrong": "❌ Faux!", "captcha_banned": "🚫 Banni 1h",
        "banned": "🚫 Banni", "maint_msg": "🛠️ Maintenance",
        "insufficient_balance": "❌ Insuffisant!", "lang_changed": "✅ Langue!",
        "ticket_chat_started": "💬 Chat ouvert!", "ticket_closed": "🔒 #{tid} fermé",
        "ticket_reply_from_support": "💬 #{tid}\n\n{reply}", "ticket_abuse_warn": "⚠️ Attention!",
        "ticket_user_msg": "👤 {msg}",
        "gw_welcome_claim": "🎁 <b>Bienvenue!</b>\n\n💎 {reward}\n👥 {remaining}/{max}\n⏰ {time}",
        "gw_claim_btn": "🎁 Réclamer",
        "gw_success": "🎊 <b>Félicitations!</b>\n\n💎 +{reward}\n💰 {balance}",
        "gw_already_claimed": "⚠️ Déjà réclamé!",
        "gw_expired": "⏰ Expiré!",
        "gw_full": "😢 Complet!",
        "gw_invalid": "❌ Invalide",
        "buy_step_1": "⏳ <b>Paiement...</b>",
        "buy_step_2": "🔐 <b>Préparation...</b>",
        "buy_step_3": "📦 <b>Emballage...</b>",
        "buy_step_4": "🎁 <b>Livraison...</b>",
        "buy_gift_msg": "🎁 <b>Profitez!</b>",
        "notif_updated_on": "✅ Notifications ACTIVÉES 🔔",
        "notif_updated_off": "✅ Notifications DÉSACTIVÉES 🔕",
    },
    "es": {
        "welcome": "🌟 <b>¡Bienvenido!</b>\n\n🌐 Elige tu idioma:",
        "must_join": "🔐 ¡Únete al canal!",
        "check_btn": "✅ Verificar", "join_channel": "📢 Unirse",
        "main_menu_title": "🏠 <b>¡Hola {name}!</b>\n\n✨ <i>Elige:</i>",
        "btn_account": "👤 Cuenta", "btn_shop": "🛍️ Tienda", "btn_rewards": "🎁 Premios",
        "btn_entertainment": "🎮 Juegos", "btn_support": "💬 Soporte", "btn_settings": "⚙️ Ajustes",
        "btn_admin": "👑 Admin", "btn_back": "🔙 Atrás",
        "account_title": "👤 <b>━━ Mi Cuenta ━━</b>", "account_desc": "✨ Tu info",
        "btn_balance": "💰 Saldo", "btn_my_id": "🆔 Info", "btn_my_rank": "🏆 Rango",
        "btn_referral": "🔗 Referidos", "btn_my_purchases": "📜 Compras",
        "rewards_title": "🎁 <b>━━ Premios ━━</b>", "rewards_desc": "✨ ¡Reclama!",
        "btn_daily_bonus": "✨ Diario", "btn_redeem_code": "🎫 Código", "btn_quests": "🔥 Misiones",
        "btn_flash_sale": "⚡ Flash",
        "entertainment_title": "🎮 <b>━━ Juegos ━━</b>", "entertainment_desc": "🎲 ¡Juega!",
        "btn_lootbox": "🎰 Caja", "btn_wheel": "🎡 Ruleta", "btn_leaderboard": "🏆 Top",
        "support_title": "💬 <b>━━ Soporte ━━</b>", "support_desc": "🤝 ¡Ayuda!",
        "btn_new_ticket": "🎫 Nuevo", "btn_my_tickets": "📋 Tickets",
        "btn_request_product": "💡 Solicitar", "btn_faq": "❓ FAQ",
        "settings_title": "⚙️ <b>━━ Ajustes ━━</b>", "settings_desc": "🎨 Personaliza!",
        "btn_change_lang": "🌐 Idioma", "btn_notifications": "🔔 Notificaciones",
        "btn_theme": "🎨 Tema", "btn_privacy": "🔒 Privacidad", "btn_about": "ℹ️ Acerca de",
        "btn_bot_dev": "Desarrollador",
        "maintenance_on": "🛠️ <b>Mantenimiento ON</b>",
        "maintenance_off": "✅ <b>Mantenimiento OFF</b>",
        "dev_info": "💻 <b>Desarrollador:</b> @fkLJh00302",
        "balance_display": "💰 {uid}\n💵 {points} 💎\n🏆 {rank}\n🎯 {discount}%\n🔥 {streak}",
        "daily_success": "🎁 +{gift} 💎\n💰 {balance}\n🔥 {streak}", "daily_wait": "⏳ {hours}h {mins}m\n🔥 {streak}",
        "streak_bonus": "🔥 {streak} días!\n🎁 +{bonus}", "referral_msg": "🔗 {invites}\n💵 {total}\n<code>{link}</code>",
        "shop_header": "🛍️ 💰 {points} | 🎯 {disc}%", "shop_empty": "📭 Vacía",
        "purchase_success": "🎉 {prod}\n{plan}\n{price}\n\n🔐 <code>{key}</code>",
        "ticket_categories": "🎫 <b>Tipo:</b>", "ticket_write": "💬 Mensaje:",
        "ticket_created": "✅ #{tid}", "my_tickets_title": "📋", "no_tickets": "📭",
        "flash_sale_active": "⚡ {discount}%\n📦 {product}\n⏰ {remaining}", "no_flash_sale": "😴",
        "leaderboard_title": "🏆 <b>━━ Top ━━</b>\n",
        "notif_on": "🔔 ON", "notif_off": "🔕 OFF",
        "theme_title": "🎨", "privacy_title": "🔒", "about_title": "ℹ️ v3.0\n👥 {users}\n🛒 {sales}",
        "faq_title": "❓ FAQ", "captcha_title": "🛡️ <b>{name}</b> {emoji}",
        "captcha_correct": "✅", "captcha_wrong": "❌", "captcha_banned": "🚫 1h",
        "banned": "🚫", "maint_msg": "🛠️", "insufficient_balance": "❌",
        "lang_changed": "✅ ¡Idioma!", "ticket_chat_started": "💬 Chat!",
        "ticket_closed": "🔒 #{tid}", "ticket_reply_from_support": "💬 {reply}",
        "ticket_abuse_warn": "⚠️", "ticket_user_msg": "👤 {msg}",
        "gw_welcome_claim": "🎁 <b>¡Bienvenido!</b>\n\n💎 {reward}\n👥 {remaining}/{max}\n⏰ {time}",
        "gw_claim_btn": "🎁 Reclamar",
        "gw_success": "🎊 <b>¡Felicidades!</b>\n\n💎 +{reward}\n💰 {balance}",
        "gw_already_claimed": "⚠️ ¡Ya reclamaste!",
        "gw_expired": "⏰ ¡Expiró!",
        "gw_full": "😢 ¡Lleno!",
        "gw_invalid": "❌ Inválido",
        "buy_step_1": "⏳ <b>Procesando...</b>",
        "buy_step_2": "🔐 <b>Preparando...</b>",
        "buy_step_3": "📦 <b>Empacando...</b>",
        "buy_step_4": "🎁 <b>Entregando...</b>",
        "buy_gift_msg": "🎁 <b>¡Disfruta!</b>",
        "notif_updated_on": "✅ Notificaciones ON 🔔",
        "notif_updated_off": "✅ Notificaciones OFF 🔕",
    },
    "vi": {
        "welcome": "🌟 <b>Chào mừng!</b>\n\n🌐 Chọn ngôn ngữ:",
        "must_join": "🔐 Tham gia kênh!",
        "check_btn": "✅ Kiểm tra", "join_channel": "📢 Tham gia",
        "main_menu_title": "🏠 <b>Chào {name}!</b>\n\n✨ <i>Chọn:</i>",
        "btn_account": "👤 Tài khoản", "btn_shop": "🛍️ Cửa hàng", "btn_rewards": "🎁 Thưởng",
        "btn_entertainment": "🎮 Giải trí", "btn_support": "💬 Hỗ trợ", "btn_settings": "⚙️ Cài đặt",
        "btn_admin": "👑 Admin", "btn_back": "🔙 Quay lại",
        "account_title": "👤 <b>━━ Tài khoản ━━</b>", "account_desc": "✨ Thông tin",
        "btn_balance": "💰 Số dư", "btn_my_id": "🆔 Info", "btn_my_rank": "🏆 Cấp",
        "btn_referral": "🔗 Giới thiệu", "btn_my_purchases": "📜 Đơn hàng",
        "rewards_title": "🎁 <b>━━ Thưởng ━━</b>", "rewards_desc": "✨ Nhận!",
        "btn_daily_bonus": "✨ Hàng ngày", "btn_redeem_code": "🎫 Mã", "btn_quests": "🔥 Nhiệm vụ",
        "btn_flash_sale": "⚡ Flash",
        "entertainment_title": "🎮 <b>━━ Giải trí ━━</b>", "entertainment_desc": "🎲 Chơi!",
        "btn_lootbox": "🎰 Hộp", "btn_wheel": "🎡 Vòng quay", "btn_leaderboard": "🏆 BXH",
        "support_title": "💬 <b>━━ Hỗ trợ ━━</b>", "support_desc": "🤝 Sẵn sàng!",
        "btn_new_ticket": "🎫 Mới", "btn_my_tickets": "📋 Vé",
        "btn_request_product": "💡 Yêu cầu", "btn_faq": "❓ FAQ",
        "settings_title": "⚙️ <b>━━ Cài đặt ━━</b>", "settings_desc": "🎨 Tùy chỉnh!",
        "btn_change_lang": "🌐 Ngôn ngữ", "btn_notifications": "🔔 Thông báo",
        "btn_theme": "🎨 Giao diện", "btn_privacy": "🔒 Riêng tư", "btn_about": "ℹ️ Giới thiệu",
        "btn_bot_dev": "Nhà phát triển",
        "maintenance_on": "🛠️ <b>Bảo trì ON</b>",
        "maintenance_off": "✅ <b>Bảo trì OFF</b>",
        "dev_info": "💻 <b>Nhà phát triển:</b> @fkLJh00302",
        "balance_display": "💰 {uid}\n💵 {points}\n🏆 {rank}\n🔥 {streak}",
        "daily_success": "🎁 +{gift}\n💰 {balance}\n🔥 {streak}", "daily_wait": "⏳ {hours}h {mins}p\n🔥 {streak}",
        "streak_bonus": "🔥 {streak}!\n🎁 +{bonus}", "referral_msg": "🔗 {invites}\n<code>{link}</code>",
        "shop_header": "🛍️ 💰 {points} | 🎯 {disc}%", "shop_empty": "📭",
        "purchase_success": "🎉 {prod}\n{plan}\n🔐 <code>{key}</code>",
        "ticket_categories": "🎫 <b>Loại:</b>", "ticket_write": "💬 Tin nhắn:",
        "ticket_created": "✅ #{tid}", "my_tickets_title": "📋", "no_tickets": "📭",
        "flash_sale_active": "⚡ {discount}%\n📦 {product}\n⏰ {remaining}", "no_flash_sale": "😴",
        "leaderboard_title": "🏆 <b>━━ BXH ━━</b>\n",
        "notif_on": "🔔 ON", "notif_off": "🔕 OFF",
        "theme_title": "🎨", "privacy_title": "🔒", "about_title": "ℹ️ v3.0\n👥 {users}\n🛒 {sales}",
        "faq_title": "❓ FAQ", "captcha_title": "🛡️ <b>{name}</b> {emoji}",
        "captcha_correct": "✅", "captcha_wrong": "❌", "captcha_banned": "🚫 1h",
        "banned": "🚫", "maint_msg": "🛠️", "insufficient_balance": "❌",
        "lang_changed": "✅ Đã đổi!", "ticket_chat_started": "💬 Chat!",
        "ticket_closed": "🔒 #{tid}", "ticket_reply_from_support": "💬 {reply}",
        "ticket_abuse_warn": "⚠️", "ticket_user_msg": "👤 {msg}",
        "gw_welcome_claim": "🎁 <b>Chào mừng!</b>\n\n💎 {reward}\n👥 {remaining}/{max}\n⏰ {time}",
        "gw_claim_btn": "🎁 Nhận thưởng",
        "gw_success": "🎊 <b>Chúc mừng!</b>\n\n💎 +{reward}\n💰 {balance}",
        "gw_already_claimed": "⚠️ Đã nhận rồi!",
        "gw_expired": "⏰ Hết hạn!",
        "gw_full": "😢 Đã đầy!",
        "gw_invalid": "❌ Không hợp lệ",
        "buy_step_1": "⏳ <b>Xử lý...</b>",
        "buy_step_2": "🔐 <b>Chuẩn bị...</b>",
        "buy_step_3": "📦 <b>Đóng gói...</b>",
        "buy_step_4": "🎁 <b>Giao hàng...</b>",
        "buy_gift_msg": "🎁 <b>Thưởng thức!</b>",
        "notif_updated_on": "✅ Thông báo BẬT 🔔",
        "notif_updated_off": "✅ Thông báo TẮT 🔕",
    }
}

# Subscription screen copy is kept in every supported locale.
_SUBSCRIPTION_LOCALE = {
    "must_join": "🔐 يرجى الانضمام إلى القنوات المطلوبة أولاً" ,
    "check_btn": "✅ تحقق من الاشتراك",
    "join_channel": "📢 انضمام إلى القناة",
    "subscription_admin": "🔐 إدارة الاشتراك الإجباري",
}
for _lang in ("ar", "en", "fr", "es", "vi"):
    for _key, _value in _SUBSCRIPTION_LOCALE.items():
        LOCALES.setdefault(_lang, {}).setdefault(_key, _value)

# Extra user-facing copy added outside the large locale block so every
# supported language stays complete without deleting or rewriting old keys.
_SUPPLEMENTAL_LOCALES = {
    "ar": {
        "btn_vip": "👑 VIP المميز",
        "btn_stars": "⭐ تحويل النجوم لنقاط",
        "btn_minigames": "🎮 الألعاب المصغرة",
        "btn_close": "❌ إغلاق القائمة",
        "menu_placeholder": "📋 القائمة",
        "ui_on": "مفعّل",
        "ui_off": "معطّل",
        "fallback_unknown": "🤔 <b>لم أفهم رسالتك!</b>\n\n💡 استخدم أزرار القائمة أدناه للتنقل\n🏠 أو أرسل /start لفتح القائمة الرئيسية",
        "captcha_solve_first": "🛡️ <b>حل التحقق الأمني أولاً!</b>",
        "maintenance_notice": "🛠️ <b>البوت تحت الصيانة مؤقتاً</b>\n\n⏳ سنعود قريباً، شكراً لصبرك!",
        "redeem_prompt": "🎁 <b>━━ استرداد كود ━━</b>\n\n✍️ أرسل الكود الخاص بك:",
        "request_product_prompt": "💡 <b>━━ طلب منتج ━━</b>\n\n✍️ اكتب اسم المنتج والتفاصيل:",
        "ticket_category_selected": "🎫 <b>النوع:</b> {category}\n\n{write}",
        "ticket_type_message": "💬 <i>اكتب رسالتك...</i>",
        "vip_member_title": "👑 <b>━━ عضو VIP ━━</b>",
        "vip_membership_title": "👑 <b>━━ عضوية VIP ━━</b>",
        "vip_you_are_vip": "🌟 <b>أنت عضو VIP!</b>",
        "vip_become": "🌟 <b>انضم إلى أعضاء VIP!</b>",
        "vip_days_remaining": "⏰ <b>الأيام المتبقية:</b> {days}",
        "vip_benefits_title": "💎 <b>المزايا الحصرية:</b>",
        "vip_benefit_daily": "🎁 مكافأة يومية مضاعفة 2x",
        "vip_benefit_discount": "💰 خصم 15% على الكل",
        "vip_benefit_stock": "📊 تفاصيل مخزون متقدمة",
        "vip_benefit_code": "🎫 كود مجاني أسبوعياً",
        "vip_benefit_support": "⚡ دعم بأولوية",
        "vip_benefit_games": "🎰 خصم 50% على الألعاب",
        "vip_benefit_badge": "👑 شارة VIP",
        "vip_monthly": "💳 <b>شهرياً:</b> {price} ⭐",
        "vip_duration": "⏰ <b>المدة:</b> 30 يوماً",
        "vip_view_stock": "📊 عرض تفاصيل المخزون",
        "btn_vip_benefits": "💎 مزايا VIP",
        "vip_weekly_code": "🎫 الحصول على الكود الأسبوعي",
        "vip_convert_stars": "⭐ تحويل النجوم إلى نقاط",
        "vip_renew": "🔄 تجديد VIP",
        "vip_subscribe": "👑 اشتراك ({price} ⭐)",
        "vip_refresh": "🔄 تحديث",
        "stars_title": "⭐ <b>━━ تحويل النجوم إلى نقاط ━━</b>",
        "stars_intro": "💫 <b>حوّل Telegram Stars فوراً!</b>",
        "stars_rate": "⭐ <b>السعر:</b> 1 ⭐ = {rate} 💎",
        "stars_delivery": "⚡ <b>التسليم:</b> فوري",
        "stars_secure": "🔒 <b>الأمان:</b> 100%",
        "stars_choose_amount": "👇 <b>اختر الكمية:</b>",
        "payment_invoice_sent": "💳 تم إرسال فاتورة الدفع!",
        "vip_only_alert": "❌ هذه الميزة لأعضاء VIP فقط!",
        "vip_weekly_wait": "⏰ عد بعد {days} يوم/أيام!",
        "vip_weekly_success": "🎉 مكافأة VIP الأسبوعية! +{reward} 💎",
        "vip_invoice_label": "VIP شهري",
        "stars_invoice_label": "{stars} نجمة",
        "payment_vip_title": "👑 عضوية VIP",
        "payment_vip_desc": "احصل على VIP لمدة 30 يوماً!\n\n✨ المزايا:\n• مكافأة يومية 2x\n• خصم 15%\n• كود أسبوعي مجاني\n• دعم بأولوية",
        "payment_stars_title": "⭐ {stars} = {points} 💎",
        "payment_stars_desc": "حوّل {stars} نجمة إلى {points} نقطة!\n\n⚡ تسليم فوري",
    },
    "en": {
        "btn_vip": "👑 VIP Premium",
        "btn_stars": "⭐ Convert Stars to Points",
        "btn_minigames": "🎮 Mini Games",
        "btn_close": "❌ Close Menu",
        "menu_placeholder": "📋 Menu",
        "ui_on": "ON",
        "ui_off": "OFF",
        "fallback_unknown": "🤔 <b>I didn't understand that!</b>\n\n💡 Use the menu buttons below to navigate\n🏠 Or send /start to open the main menu",
        "captcha_solve_first": "🛡️ <b>Please solve the security check first!</b>",
        "maintenance_notice": "🛠️ <b>The bot is temporarily under maintenance</b>\n\n⏳ We will be back soon. Thank you for your patience!",
        "redeem_prompt": "🎁 <b>━━ Redeem Code ━━</b>\n\n✍️ Send your code:",
        "request_product_prompt": "💡 <b>━━ Request Product ━━</b>\n\n✍️ Write the product name and details:",
        "ticket_category_selected": "🎫 <b>Category:</b> {category}\n\n{write}",
        "ticket_type_message": "💬 <i>Type your message...</i>",
        "vip_member_title": "👑 <b>━━ VIP Member ━━</b>",
        "vip_membership_title": "👑 <b>━━ VIP Membership ━━</b>",
        "vip_you_are_vip": "🌟 <b>You are a VIP!</b>",
        "vip_become": "🌟 <b>Become a VIP member!</b>",
        "vip_days_remaining": "⏰ <b>Days remaining:</b> {days}",
        "vip_benefits_title": "💎 <b>Exclusive benefits:</b>",
        "vip_benefit_daily": "🎁 2x daily bonus",
        "vip_benefit_discount": "💰 15% discount on everything",
        "vip_benefit_stock": "📊 Advanced stock info",
        "vip_benefit_code": "🎫 Weekly free code",
        "vip_benefit_support": "⚡ Priority support",
        "vip_benefit_games": "🎰 50% off games",
        "vip_benefit_badge": "👑 VIP badge",
        "vip_monthly": "💳 <b>Monthly:</b> {price} ⭐",
        "vip_duration": "⏰ <b>Duration:</b> 30 days",
        "vip_view_stock": "📊 View stock details",
        "btn_vip_benefits": "💎 VIP Benefits",
        "vip_weekly_code": "🎫 Get weekly code",
        "vip_convert_stars": "⭐ Convert Stars to points",
        "vip_renew": "🔄 Renew VIP",
        "vip_subscribe": "👑 Subscribe ({price} ⭐)",
        "vip_refresh": "🔄 Refresh",
        "stars_title": "⭐ <b>━━ Stars to Points ━━</b>",
        "stars_intro": "💫 <b>Convert Telegram Stars instantly!</b>",
        "stars_rate": "⭐ <b>Rate:</b> 1 ⭐ = {rate} 💎",
        "stars_delivery": "⚡ <b>Delivery:</b> Instant",
        "stars_secure": "🔒 <b>Secure:</b> 100%",
        "stars_choose_amount": "👇 <b>Choose amount:</b>",
        "payment_invoice_sent": "💳 Payment invoice sent!",
        "vip_only_alert": "❌ VIP only!",
        "vip_weekly_wait": "⏰ Come back in {days} day(s)!",
        "vip_weekly_success": "🎉 Weekly VIP bonus! +{reward} 💎",
        "vip_invoice_label": "VIP Monthly",
        "stars_invoice_label": "{stars} Stars",
        "payment_vip_title": "👑 VIP Membership",
        "payment_vip_desc": "Get VIP for 30 days!\n\n✨ Benefits:\n• 2x daily bonus\n• 15% discount\n• Weekly free code\n• Priority support",
        "payment_stars_title": "⭐ {stars} = {points} 💎",
        "payment_stars_desc": "Convert {stars} Stars to {points} points!\n\n⚡ Instant delivery",
    },
    "fr": {
        "btn_vip": "👑 VIP Premium",
        "btn_stars": "⭐ Convertir les Stars en points",
        "btn_minigames": "🎮 Mini-jeux",
        "btn_close": "❌ Fermer le menu",
        "menu_placeholder": "📋 Menu",
        "ui_on": "ACTIVÉ",
        "ui_off": "DÉSACTIVÉ",
        "fallback_unknown": "🤔 <b>Je n'ai pas compris!</b>\n\n💡 Utilisez les boutons du menu ci-dessous\n🏠 Ou envoyez /start pour ouvrir le menu principal",
        "captcha_solve_first": "🛡️ <b>Veuillez d'abord terminer la vérification!</b>",
        "maintenance_notice": "🛠️ <b>Le bot est temporairement en maintenance</b>\n\n⏳ Nous revenons bientôt. Merci pour votre patience!",
        "redeem_prompt": "🎁 <b>━━ Utiliser un code ━━</b>\n\n✍️ Envoyez votre code:",
        "request_product_prompt": "💡 <b>━━ Demande de produit ━━</b>\n\n✍️ Écrivez le nom du produit et les détails:",
        "ticket_category_selected": "🎫 <b>Catégorie:</b> {category}\n\n{write}",
        "ticket_type_message": "💬 <i>Écrivez votre message...</i>",
        "vip_member_title": "👑 <b>━━ Membre VIP ━━</b>",
        "vip_membership_title": "👑 <b>━━ Abonnement VIP ━━</b>",
        "vip_you_are_vip": "🌟 <b>Vous êtes VIP!</b>",
        "vip_become": "🌟 <b>Devenez membre VIP!</b>",
        "vip_days_remaining": "⏰ <b>Jours restants:</b> {days}",
        "vip_benefits_title": "💎 <b>Avantages exclusifs:</b>",
        "vip_benefit_daily": "🎁 Bonus quotidien x2",
        "vip_benefit_discount": "💰 15% de réduction sur tout",
        "vip_benefit_stock": "📊 Infos de stock avancées",
        "vip_benefit_code": "🎫 Code gratuit chaque semaine",
        "vip_benefit_support": "⚡ Support prioritaire",
        "vip_benefit_games": "🎰 50% sur les jeux",
        "vip_benefit_badge": "👑 Badge VIP",
        "vip_monthly": "💳 <b>Mensuel:</b> {price} ⭐",
        "vip_duration": "⏰ <b>Durée:</b> 30 jours",
        "vip_view_stock": "📊 Voir le stock",
        "btn_vip_benefits": "💎 Avantages VIP",
        "vip_weekly_code": "🎫 Obtenir le code hebdomadaire",
        "vip_convert_stars": "⭐ Convertir les Stars en points",
        "vip_renew": "🔄 Renouveler VIP",
        "vip_subscribe": "👑 S'abonner ({price} ⭐)",
        "vip_refresh": "🔄 Actualiser",
        "stars_title": "⭐ <b>━━ Stars vers points ━━</b>",
        "stars_intro": "💫 <b>Convertissez vos Telegram Stars instantanément!</b>",
        "stars_rate": "⭐ <b>Taux:</b> 1 ⭐ = {rate} 💎",
        "stars_delivery": "⚡ <b>Livraison:</b> instantanée",
        "stars_secure": "🔒 <b>Sécurité:</b> 100%",
        "stars_choose_amount": "👇 <b>Choisissez le montant:</b>",
        "payment_invoice_sent": "💳 Facture de paiement envoyée!",
        "vip_only_alert": "❌ Réservé aux VIP!",
        "vip_weekly_wait": "⏰ Revenez dans {days} jour(s)!",
        "vip_weekly_success": "🎉 Bonus VIP hebdomadaire! +{reward} 💎",
        "vip_invoice_label": "VIP mensuel",
        "stars_invoice_label": "{stars} Stars",
        "payment_vip_title": "👑 Abonnement VIP",
        "payment_vip_desc": "Obtenez le VIP pendant 30 jours!\n\n✨ Avantages:\n• Bonus quotidien x2\n• 15% de réduction\n• Code hebdomadaire gratuit\n• Support prioritaire",
        "payment_stars_title": "⭐ {stars} = {points} 💎",
        "payment_stars_desc": "Convertissez {stars} Stars en {points} points!\n\n⚡ Livraison instantanée",
    },
    "es": {
        "btn_vip": "👑 VIP Premium",
        "btn_stars": "⭐ Convertir Stars a puntos",
        "btn_minigames": "🎮 Minijuegos",
        "btn_close": "❌ Cerrar menú",
        "menu_placeholder": "📋 Menú",
        "ui_on": "ACTIVO",
        "ui_off": "INACTIVO",
        "fallback_unknown": "🤔 <b>¡No entendí eso!</b>\n\n💡 Usa los botones del menú de abajo\n🏠 O envía /start para abrir el menú principal",
        "captcha_solve_first": "🛡️ <b>¡Completa primero la verificación!</b>",
        "maintenance_notice": "🛠️ <b>El bot está temporalmente en mantenimiento</b>\n\n⏳ Volveremos pronto. ¡Gracias por tu paciencia!",
        "redeem_prompt": "🎁 <b>━━ Canjear código ━━</b>\n\n✍️ Envía tu código:",
        "request_product_prompt": "💡 <b>━━ Solicitar producto ━━</b>\n\n✍️ Escribe el nombre del producto y detalles:",
        "ticket_category_selected": "🎫 <b>Categoría:</b> {category}\n\n{write}",
        "ticket_type_message": "💬 <i>Escribe tu mensaje...</i>",
        "vip_member_title": "👑 <b>━━ Miembro VIP ━━</b>",
        "vip_membership_title": "👑 <b>━━ Membresía VIP ━━</b>",
        "vip_you_are_vip": "🌟 <b>¡Eres VIP!</b>",
        "vip_become": "🌟 <b>¡Hazte miembro VIP!</b>",
        "vip_days_remaining": "⏰ <b>Días restantes:</b> {days}",
        "vip_benefits_title": "💎 <b>Beneficios exclusivos:</b>",
        "vip_benefit_daily": "🎁 Bono diario x2",
        "vip_benefit_discount": "💰 15% de descuento en todo",
        "vip_benefit_stock": "📊 Información avanzada de stock",
        "vip_benefit_code": "🎫 Código gratis semanal",
        "vip_benefit_support": "⚡ Soporte prioritario",
        "vip_benefit_games": "🎰 50% en juegos",
        "vip_benefit_badge": "👑 Insignia VIP",
        "vip_monthly": "💳 <b>Mensual:</b> {price} ⭐",
        "vip_duration": "⏰ <b>Duración:</b> 30 días",
        "vip_view_stock": "📊 Ver stock",
        "btn_vip_benefits": "💎 Beneficios VIP",
        "vip_weekly_code": "🎫 Obtener código semanal",
        "vip_convert_stars": "⭐ Convertir Stars a puntos",
        "vip_renew": "🔄 Renovar VIP",
        "vip_subscribe": "👑 Suscribirse ({price} ⭐)",
        "vip_refresh": "🔄 Actualizar",
        "stars_title": "⭐ <b>━━ Stars a puntos ━━</b>",
        "stars_intro": "💫 <b>¡Convierte Telegram Stars al instante!</b>",
        "stars_rate": "⭐ <b>Tasa:</b> 1 ⭐ = {rate} 💎",
        "stars_delivery": "⚡ <b>Entrega:</b> instantánea",
        "stars_secure": "🔒 <b>Seguridad:</b> 100%",
        "stars_choose_amount": "👇 <b>Elige cantidad:</b>",
        "payment_invoice_sent": "💳 ¡Factura de pago enviada!",
        "vip_only_alert": "❌ ¡Solo VIP!",
        "vip_weekly_wait": "⏰ ¡Vuelve en {days} día(s)!",
        "vip_weekly_success": "🎉 ¡Bono VIP semanal! +{reward} 💎",
        "vip_invoice_label": "VIP mensual",
        "stars_invoice_label": "{stars} Stars",
        "payment_vip_title": "👑 Membresía VIP",
        "payment_vip_desc": "¡Obtén VIP por 30 días!\n\n✨ Beneficios:\n• Bono diario x2\n• 15% de descuento\n• Código semanal gratis\n• Soporte prioritario",
        "payment_stars_title": "⭐ {stars} = {points} 💎",
        "payment_stars_desc": "¡Convierte {stars} Stars en {points} puntos!\n\n⚡ Entrega instantánea",
    },
    "vi": {
        "btn_vip": "👑 VIP Premium",
        "btn_stars": "⭐ Đổi Stars thành điểm",
        "btn_minigames": "🎮 Trò chơi nhỏ",
        "btn_close": "❌ Đóng menu",
        "menu_placeholder": "📋 Menu",
        "ui_on": "BẬT",
        "ui_off": "TẮT",
        "fallback_unknown": "🤔 <b>Tôi không hiểu!</b>\n\n💡 Hãy dùng các nút menu bên dưới\n🏠 Hoặc gửi /start để mở menu chính",
        "captcha_solve_first": "🛡️ <b>Vui lòng hoàn tất xác minh trước!</b>",
        "maintenance_notice": "🛠️ <b>Bot đang bảo trì tạm thời</b>\n\n⏳ Chúng tôi sẽ sớm quay lại. Cảm ơn bạn đã kiên nhẫn!",
        "redeem_prompt": "🎁 <b>━━ Đổi mã ━━</b>\n\n✍️ Gửi mã của bạn:",
        "request_product_prompt": "💡 <b>━━ Yêu cầu sản phẩm ━━</b>\n\n✍️ Viết tên sản phẩm và chi tiết:",
        "ticket_category_selected": "🎫 <b>Loại:</b> {category}\n\n{write}",
        "ticket_type_message": "💬 <i>Nhập tin nhắn của bạn...</i>",
        "vip_member_title": "👑 <b>━━ Thành viên VIP ━━</b>",
        "vip_membership_title": "👑 <b>━━ Gói VIP ━━</b>",
        "vip_you_are_vip": "🌟 <b>Bạn là VIP!</b>",
        "vip_become": "🌟 <b>Trở thành thành viên VIP!</b>",
        "vip_days_remaining": "⏰ <b>Số ngày còn lại:</b> {days}",
        "vip_benefits_title": "💎 <b>Quyền lợi độc quyền:</b>",
        "vip_benefit_daily": "🎁 Thưởng hằng ngày x2",
        "vip_benefit_discount": "💰 Giảm 15% cho tất cả",
        "vip_benefit_stock": "📊 Thông tin kho nâng cao",
        "vip_benefit_code": "🎫 Mã miễn phí hằng tuần",
        "vip_benefit_support": "⚡ Hỗ trợ ưu tiên",
        "vip_benefit_games": "🎰 Giảm 50% trò chơi",
        "vip_benefit_badge": "👑 Huy hiệu VIP",
        "vip_monthly": "💳 <b>Hằng tháng:</b> {price} ⭐",
        "vip_duration": "⏰ <b>Thời hạn:</b> 30 ngày",
        "vip_view_stock": "📊 Xem chi tiết kho",
        "btn_vip_benefits": "💎 Quyền lợi VIP",
        "vip_weekly_code": "🎫 Nhận mã hằng tuần",
        "vip_convert_stars": "⭐ Đổi Stars thành điểm",
        "vip_renew": "🔄 Gia hạn VIP",
        "vip_subscribe": "👑 Đăng ký ({price} ⭐)",
        "vip_refresh": "🔄 Làm mới",
        "stars_title": "⭐ <b>━━ Stars thành điểm ━━</b>",
        "stars_intro": "💫 <b>Đổi Telegram Stars ngay lập tức!</b>",
        "stars_rate": "⭐ <b>Tỷ lệ:</b> 1 ⭐ = {rate} 💎",
        "stars_delivery": "⚡ <b>Giao:</b> tức thì",
        "stars_secure": "🔒 <b>An toàn:</b> 100%",
        "stars_choose_amount": "👇 <b>Chọn số lượng:</b>",
        "payment_invoice_sent": "💳 Đã gửi hóa đơn thanh toán!",
        "vip_only_alert": "❌ Chỉ dành cho VIP!",
        "vip_weekly_wait": "⏰ Quay lại sau {days} ngày!",
        "vip_weekly_success": "🎉 Thưởng VIP hằng tuần! +{reward} 💎",
        "vip_invoice_label": "VIP hằng tháng",
        "stars_invoice_label": "{stars} Stars",
        "payment_vip_title": "👑 Gói VIP",
        "payment_vip_desc": "Nhận VIP trong 30 ngày!\n\n✨ Quyền lợi:\n• Thưởng hằng ngày x2\n• Giảm 15%\n• Mã miễn phí hằng tuần\n• Hỗ trợ ưu tiên",
        "payment_stars_title": "⭐ {stars} = {points} 💎",
        "payment_stars_desc": "Đổi {stars} Stars thành {points} điểm!\n\n⚡ Giao tức thì",
    },
}
for _lang, _values in _SUPPLEMENTAL_LOCALES.items():
    LOCALES.setdefault(_lang, {}).update(_values)

_MORE_LOCALES = {
    "ar": {
        "rank_title": "🏆 <b>━━ رتبتي ━━</b>",
        "rank_current": "الحالية:",
        "rank_discount": "الخصم:",
        "rank_points": "النقاط:",
        "rank_all": "📋 <b>كل الرتب:</b>",
        "share_link": "📤 مشاركة الرابط",
        "quest_title": "🔥 <b>━━ المهام ━━</b>",
        "quest_invite": "👥 دعوة الأصدقاء",
        "quest_buy": "🛒 إتمام مشتريات",
        "quest_points": "💎 جمع النقاط",
        "quest_done": "✅ <b>مكتملة</b>",
        "join_wait_alert": "⏳ انتظر 3 ثوانٍ قبل التحقق مرة أخرى",
        "join_verified_alert": "✅ تم التحقق!",
        "join_welcome": "🎉 <b>تم التحقق بنجاح!</b>\n\n✅ يمكنك الآن استخدام كل الميزات\n🎁 <i>استمتع!</i>",
        "join_not_joined": "❌ لم تنضم بعد!",
        "join_first_alert": "⚠️ انضم إلى القناة أولاً!",
        "captcha_too_many": "🚫 <b>محاولات خاطئة كثيرة!</b>\n\n⏰ تم الحظر لمدة ساعة",
        "captcha_expired": "⏰ <b>انتهت صلاحية التحقق!</b>",
    },
    "en": {
        "rank_title": "🏆 <b>━━ My Rank ━━</b>",
        "rank_current": "Current:",
        "rank_discount": "Discount:",
        "rank_points": "Points:",
        "rank_all": "📋 <b>All ranks:</b>",
        "share_link": "📤 Share link",
        "quest_title": "🔥 <b>━━ Quests ━━</b>",
        "quest_invite": "👥 Invite friends",
        "quest_buy": "🛒 Make purchases",
        "quest_points": "💎 Collect points",
        "quest_done": "✅ <b>Done</b>",
        "join_wait_alert": "⏳ Please wait 3 seconds before checking again",
        "join_verified_alert": "✅ Verified!",
        "join_welcome": "🎉 <b>Verified successfully!</b>\n\n✅ You can now use all features\n🎁 <i>Enjoy!</i>",
        "join_not_joined": "❌ You haven't joined yet!",
        "join_first_alert": "⚠️ Join the channel first!",
        "captcha_too_many": "🚫 <b>Too many wrong attempts!</b>\n\n⏰ Banned for 1 hour",
        "captcha_expired": "⏰ <b>Captcha expired!</b>",
    },
    "fr": {
        "rank_title": "🏆 <b>━━ Mon rang ━━</b>",
        "rank_current": "Actuel:",
        "rank_discount": "Réduction:",
        "rank_points": "Points:",
        "rank_all": "📋 <b>Tous les rangs:</b>",
        "share_link": "📤 Partager le lien",
        "quest_title": "🔥 <b>━━ Missions ━━</b>",
        "quest_invite": "👥 Inviter des amis",
        "quest_buy": "🛒 Faire des achats",
        "quest_points": "💎 Collecter des points",
        "quest_done": "✅ <b>Terminé</b>",
        "join_wait_alert": "⏳ Veuillez attendre 3 secondes avant de vérifier à nouveau",
        "join_verified_alert": "✅ Vérifié!",
        "join_welcome": "🎉 <b>Vérification réussie!</b>\n\n✅ Vous pouvez maintenant utiliser toutes les fonctions\n🎁 <i>Profitez!</i>",
        "join_not_joined": "❌ Vous n'avez pas encore rejoint!",
        "join_first_alert": "⚠️ Rejoignez d'abord le canal!",
        "captcha_too_many": "🚫 <b>Trop de tentatives incorrectes!</b>\n\n⏰ Banni pendant 1 heure",
        "captcha_expired": "⏰ <b>Captcha expiré!</b>",
    },
    "es": {
        "rank_title": "🏆 <b>━━ Mi rango ━━</b>",
        "rank_current": "Actual:",
        "rank_discount": "Descuento:",
        "rank_points": "Puntos:",
        "rank_all": "📋 <b>Todos los rangos:</b>",
        "share_link": "📤 Compartir enlace",
        "quest_title": "🔥 <b>━━ Misiones ━━</b>",
        "quest_invite": "👥 Invitar amigos",
        "quest_buy": "🛒 Hacer compras",
        "quest_points": "💎 Reunir puntos",
        "quest_done": "✅ <b>Hecho</b>",
        "join_wait_alert": "⏳ Espera 3 segundos antes de verificar de nuevo",
        "join_verified_alert": "✅ ¡Verificado!",
        "join_welcome": "🎉 <b>¡Verificación correcta!</b>\n\n✅ Ya puedes usar todas las funciones\n🎁 <i>¡Disfruta!</i>",
        "join_not_joined": "❌ ¡Aún no te has unido!",
        "join_first_alert": "⚠️ ¡Únete primero al canal!",
        "captcha_too_many": "🚫 <b>¡Demasiados intentos incorrectos!</b>\n\n⏰ Bloqueado por 1 hora",
        "captcha_expired": "⏰ <b>¡Captcha expirado!</b>",
    },
    "vi": {
        "rank_title": "🏆 <b>━━ Cấp của tôi ━━</b>",
        "rank_current": "Hiện tại:",
        "rank_discount": "Giảm giá:",
        "rank_points": "Điểm:",
        "rank_all": "📋 <b>Tất cả cấp:</b>",
        "share_link": "📤 Chia sẻ liên kết",
        "quest_title": "🔥 <b>━━ Nhiệm vụ ━━</b>",
        "quest_invite": "👥 Mời bạn bè",
        "quest_buy": "🛒 Mua hàng",
        "quest_points": "💎 Thu thập điểm",
        "quest_done": "✅ <b>Hoàn thành</b>",
        "join_wait_alert": "⏳ Vui lòng đợi 3 giây trước khi kiểm tra lại",
        "join_verified_alert": "✅ Đã xác minh!",
        "join_welcome": "🎉 <b>Xác minh thành công!</b>\n\n✅ Bạn có thể dùng tất cả tính năng\n🎁 <i>Chúc vui vẻ!</i>",
        "join_not_joined": "❌ Bạn chưa tham gia!",
        "join_first_alert": "⚠️ Hãy tham gia kênh trước!",
        "captcha_too_many": "🚫 <b>Quá nhiều lần sai!</b>\n\n⏰ Bị chặn trong 1 giờ",
        "captcha_expired": "⏰ <b>Captcha đã hết hạn!</b>",
    },
}
for _lang, _values in _MORE_LOCALES.items():
    LOCALES.setdefault(_lang, {}).update(_values)

def t(lang, key, **kwargs):
    if lang not in LOCALES: lang = "en"
    txt = LOCALES[lang].get(key, LOCALES["en"].get(key, key))
    if kwargs:
        try: txt = txt.format(**kwargs)
        except: pass
    return txt
