import json

SHOP_TRANSLATIONS = {
    "ar": {
        "title": "🛍️ <b>━━ السوق المركزي ━━</b>",
        "subtitle": "✨ <i>أفضل الأدوات بأرخص الأسعار حصرياً لك</i>",
        "wallet": "💳 المحفظة",
        "rank_disc": "🛡️ خصم الرتبة",
        "flash": "⚡ عرض خاطف جنوني:",
        "off": "خصم",
        "select_prod": "👇 <b>اختر منتجاً لاستعراض التفاصيل:</b>",
        "prod_info": "📦 <b>━━ معلومات المنتج ━━</b>",
        "prod_name": "📌 <b>الاسم:</b>",
        "prod_desc_text": "🔥 <i>أقوى أداة في السوق، تحديثات مستمرة وأمان عالي جداً! لا تفوت الفرصة.</i>",
        "balance": "💰 رصيدك",
        "duration": "⏱️ <b>اختر باقة الاشتراك المناسبة لك:</b>",
        "days_1": "1 يوم", "days_7": "7 أيام", "days_30": "30 يوم",
        "stock": "المخزون", "price": "السعر", "available": "متوفر", "out": "نفد",
        "btn_buy": "🛒 شراء الآن", "btn_back": "🔙 العودة للمتجر",
        "empty": "📭 المتجر فارغ حالياً.",
        "out_alert": "⚠️ نفدت الكمية من هذا المنتج!",
        "buy_error": "❌ حدث خطأ أثناء الشراء. يرجى التواصل مع الدعم."
    },
    "en": {
        "title": "🛍️ <b>━━ CENTRAL SHOP ━━</b>",
        "subtitle": "✨ <i>Best tools at the lowest prices exclusively for you</i>",
        "wallet": "💳 Wallet",
        "rank_disc": "🛡️ Rank Discount",
        "flash": "⚡ CRAZY FLASH SALE:",
        "off": "OFF",
        "select_prod": "👇 <b>Select a product to view details:</b>",
        "prod_info": "📦 <b>━━ Product Info ━━</b>",
        "prod_name": "📌 <b>Name:</b>",
        "prod_desc_text": "🔥 <i>Top tier tool in the market, constant updates & very high security!</i>",
        "balance": "💰 Balance",
        "duration": "⏱️ <b>Choose your subscription plan:</b>",
        "days_1": "1 Day", "days_7": "7 Days", "days_30": "30 Days",
        "stock": "Stock", "price": "Price", "available": "Available", "out": "Out of stock",
        "btn_buy": "🛒 Buy Now", "btn_back": "🔙 Back to Shop",
        "empty": "📭 Shop is currently empty.",
        "out_alert": "⚠️ This product is out of stock!",
        "buy_error": "❌ Error during purchase. Please contact support."
    },
    "fr": {
        "title": "🛍️ <b>━━ BOUTIQUE CENTRALE ━━</b>",
        "subtitle": "✨ <i>Les meilleurs outils aux prix les plus bas pour vous</i>",
        "wallet": "💳 Portefeuille",
        "rank_disc": "🛡️ Réduction Rang",
        "flash": "⚡ VENTE ÉCLAIR DE FOLIE:",
        "off": "RÉDUCTION",
        "select_prod": "👇 <b>Sélectionnez un produit pour voir les détails:</b>",
        "prod_info": "📦 <b>━━ Info Produit ━━</b>",
        "prod_name": "📌 <b>Nom:</b>",
        "prod_desc_text": "🔥 <i>Meilleur outil du marché, mises à jour constantes et haute sécurité!</i>",
        "balance": "💰 Solde",
        "duration": "⏱️ <b>Choisissez votre forfait d'abonnement:</b>",
        "days_1": "1 Jour", "days_7": "7 Jours", "days_30": "30 Jours",
        "stock": "Stock", "price": "Prix", "available": "Disponible", "out": "Épuisé",
        "btn_buy": "🛒 Acheter", "btn_back": "🔙 Retour Boutique",
        "empty": "📭 La boutique est actuellement vide.",
        "out_alert": "⚠️ Ce produit est en rupture de stock!",
        "buy_error": "❌ Erreur lors de l'achat. Veuillez contacter le support."
    },
    "es": {
        "title": "🛍️ <b>━━ TIENDA CENTRAL ━━</b>",
        "subtitle": "✨ <i>Las mejores herramientas a los precios más bajos</i>",
        "wallet": "💳 Billetera",
        "rank_disc": "🛡️ Descuento Rango",
        "flash": "⚡ OFERTA RELÁMPAGO:",
        "off": "DESCUENTO",
        "select_prod": "👇 <b>Selecciona un producto para ver detalles:</b>",
        "prod_info": "📦 <b>━━ Info de Producto ━━</b>",
        "prod_name": "📌 <b>Nombre:</b>",
        "prod_desc_text": "🔥 <i>¡La mejor herramienta, actualizaciones constantes y alta seguridad!</i>",
        "balance": "💰 Saldo",
        "duration": "⏱️ <b>Elige tu plan de suscripción:</b>",
        "days_1": "1 Día", "days_7": "7 Días", "days_30": "30 Días",
        "stock": "Stock", "price": "Precio", "available": "Disponible", "out": "Agotado",
        "btn_buy": "🛒 Comprar", "btn_back": "🔙 Volver a Tienda",
        "empty": "📭 La tienda está vacía.",
        "out_alert": "⚠️ ¡Este producto está agotado!",
        "buy_error": "❌ Error durante la compra. Por favor, contacte al soporte."
    },
    "vi": {
        "title": "🛍️ <b>━━ CỬA HÀNG TRUNG TÂM ━━</b>",
        "subtitle": "✨ <i>Công cụ tốt nhất với giá rẻ nhất dành cho bạn</i>",
        "wallet": "💳 Ví",
        "rank_disc": "🛡️ Giảm giá Hạng",
        "flash": "⚡ SIÊU GIẢM GIÁ:",
        "off": "GIẢM",
        "select_prod": "👇 <b>Chọn sản phẩm để xem chi tiết:</b>",
        "prod_info": "📦 <b>━━ Thông tin Sản phẩm ━━</b>",
        "prod_name": "📌 <b>Tên:</b>",
        "prod_desc_text": "🔥 <i>Công cụ tốt nhất thị trường, cập nhật liên tục & bảo mật rất cao!</i>",
        "balance": "💰 Số dư",
        "duration": "⏱️ <b>Chọn gói đăng ký của bạn:</b>",
        "days_1": "1 Ngày", "days_7": "7 Ngày", "days_30": "30 Ngày",
        "stock": "Kho", "price": "Giá", "available": "Có sẵn", "out": "Hết hàng",
        "btn_buy": "🛒 Mua ngay", "btn_back": "🔙 Trở lại Cửa hàng",
        "empty": "📭 Cửa hàng hiện đang trống.",
        "out_alert": "⚠️ Sản phẩm này đã hết hàng!",
        "buy_error": "❌ Lỗi trong quá trình mua. Vui lòng liên hệ hỗ trợ."
    }
}

def gt_shop(lang, key):
    return SHOP_TRANSLATIONS.get(lang, SHOP_TRANSLATIONS["en"]).get(key, key)
